# -*- mode: k8s -*-
{{ if .Values.hosts -}}
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: {{ template "symfony.fullname" . }}-web
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: 'web'
    traefik.ingress.kubernetes.io/router.middlewares: 'default-redirect-to-https@kubernetescrd'
spec:
  rules:
{{- range .Values.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "symfony.fullname" $ }}
              servicePort: 80
{{- end }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: {{ template "symfony.fullname" . }}-websecure
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
spec:
  rules:
{{- range .Values.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "symfony.fullname" $ }}
              servicePort: 80
{{- end }}
{{- end }}
