# -*- mode: k8s -*-
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
