# -*- mode: k8s -*-
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
stringData:
  password: {{ tpl .Values.password . | quote }}
