image:
  repository: 'changeMe'
  tag: 'changeMe'

updateStrategy:
  type: Recreate

imagePullSecrets: []

extraVolumes: []
extraAppVolumeMounts: []
extraAppContainers: []
extraContainers: []

defaultConfig: ''
hosts: []
